"""empty message

Revision ID: 1ce8a13fd79d
Revises: 09a1fc406488
Create Date: 2024-04-18 17:26:02.218578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ce8a13fd79d'
down_revision: Union[str, None] = '09a1fc406488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.alter_column('admin_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_column('name')

    with op.batch_alter_table('bonuses', schema=None) as batch_op:
        batch_op.alter_column('admin_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
