"""history

Revision ID: b08af31f7d4c
Revises: a692bff01c24
Create Date: 2024-04-10 23:14:41.492648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08af31f7d4c'
down_revision: Union[str, None] = 'a692bff01c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonus_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bonus_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bonus_id'], ['bonuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bonuses', sa.Column('expire_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bonuses', 'expire_date')
    op.drop_table('bonus_history')
    # ### end Alembic commands ###
