"""Correct visit model.

Revision ID: c4740de210fc
Revises: b534e48937b3
Create Date: 2024-04-22 01:04:22.293129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4740de210fc'
down_revision: Union[str, None] = 'b534e48937b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.String(length=120), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'services', ['services'], ['name'])
        batch_op.drop_column('bonus_payment')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('bonus_payment', sa.BOOLEAN(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'])
        batch_op.drop_column('services')

    # ### end Alembic commands ###
