"""empty message

Revision ID: f4b78f3231ac
Revises: 35f443c61699
Create Date: 2024-04-14 20:21:41.023294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4b78f3231ac'
down_revision: Union[str, None] = '35f443c61699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###
